chore: "outDir" causes issues with how gulp uses files, (#76)
@see https://github.com/ivogabe/gulp-typescript/issues/143

with "outDir" the following dist structure is created

```
angular2-seed git:(systemjs)>ls dist
app          bootstrap.js index.html   src          vendor
```

throws this error in the browser:
  `bootstrap.js:11 Error: SyntaxError: Unexpected token <(…)`

the bootstrap.js has:
```
System.import('./app.js')...
```
which implies the intent is to be in the same dir or at
the very least not in a src dir within the dist.
(also doesn't make sent to have an dist/app and dist/src)

removing "outDir" in tsconfig.json, alleviates the issue